name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  ci:
    strategy:
      matrix:
        command: ['build', 'build:staging']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: clean install
        run: npm ci
      - name: ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
