name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  ci:
    strategy:
      matrix:
        command: ['build', 'build:staging']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: clean install
        run: npm ci
      - name: ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
      - name: ensure hugo_stats.json populated with > 100 lines
        run: |
          if [ $(wc -l < ./hugo_stats.json) -gt 100 ]; then
            echo "hugo_stats.json populated with > 100 lines"
          else
            echo "hugo_stats.json not populated with > 100 lines"
            exit 1
          fi