name: DeployStaging
on:
  push:
    branches:
      - trunk

env:
  URL: 'dev3.atsign.wtf'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  deploy:
    if: ${{ github.repository == 'atsign-foundation/docs.atsign.com' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Staging
        run: npm run build:staging

      - name: Deploy Staging
        uses: peaceiris/actions-gh-pages@64b46b4226a4a12da2239ba3ea5aa73e3163c75b # v3
        with:
          personal_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: ${{ env.URL }}
