name: DeployStaging
on:
  push:
    branches:
      - trunk

env:
  URL: 'dev3.atsign.wtf'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  deploy:
    if: ${{ github.repository == 'atsign-foundation/docs.atsign.com' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Staging
        run: npm run build:staging

      - name: Deploy Staging
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935 # v3
        with:
          personal_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: ${{ env.URL }}
